[package]
authors = ["Dustin J. Mitchell <dustin@mozilla.com>"]
edition = "2018"
name = "giphyproxy"
version = "0.1.0"

[dependencies]
anyhow = "1"
env_logger = "0.8"
log = "0.4"

[dependencies.tokio]
features = ["full"]
version = "1"
